backend:
  name: git-gateway
  branch: master

media_folder: "src/img"

collections:
  - name: "idiomas"
    label: "Idiomas"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner", name: "bannerUrl", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "dicas"
    label: "Dicas"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
