backend:
  name: git-gateway
  branch: master

media_folder: "src/img"

collections:
  - name: "idiomas"
    label: "Idiomas"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Banner", name: "bannerUrl", widget: "image", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }
  - name: "dicas"
    label: "Dicas"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Data", name: "date", widget: "datetime", required: false }
      - { label: "Banner", name: "bannerUrl", widget: "image", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }
